//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantReviewService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Restaurant", Namespace="http://schemas.datacontract.org/2004/07/AlgonquinCollege.OnlineService.Restaurant" +
        "Review")]
    public partial class Restaurant : object
    {
        
        private string NameField;
        
        private int RatingField;
        
        private string SummaryField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Rating
        {
            get
            {
                return this.RatingField;
            }
            set
            {
                this.RatingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Summary
        {
            get
            {
                return this.SummaryField;
            }
            set
            {
                this.SummaryField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RestaurantReviewService.IRestaurantReviewService")]
    public interface IRestaurantReviewService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestaurantReviewService/GetAllRestaurants", ReplyAction="http://tempuri.org/IRestaurantReviewService/GetAllRestaurantsResponse")]
        System.Threading.Tasks.Task<RestaurantReviewService.Restaurant[]> GetAllRestaurantsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestaurantReviewService/GetRestaurantByName", ReplyAction="http://tempuri.org/IRestaurantReviewService/GetRestaurantByNameResponse")]
        System.Threading.Tasks.Task<RestaurantReviewService.Restaurant[]> GetRestaurantByNameAsync(string RestaurantName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestaurantReviewService/GetRestaurantByRating", ReplyAction="http://tempuri.org/IRestaurantReviewService/GetRestaurantByRatingResponse")]
        System.Threading.Tasks.Task<RestaurantReviewService.Restaurant[]> GetRestaurantByRatingAsync(int Rating);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface IRestaurantReviewServiceChannel : RestaurantReviewService.IRestaurantReviewService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class RestaurantReviewServiceClient : System.ServiceModel.ClientBase<RestaurantReviewService.IRestaurantReviewService>, RestaurantReviewService.IRestaurantReviewService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public RestaurantReviewServiceClient() : 
                base(RestaurantReviewServiceClient.GetDefaultBinding(), RestaurantReviewServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IRestaurantReviewService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RestaurantReviewServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(RestaurantReviewServiceClient.GetBindingForEndpoint(endpointConfiguration), RestaurantReviewServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RestaurantReviewServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(RestaurantReviewServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RestaurantReviewServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(RestaurantReviewServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RestaurantReviewServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<RestaurantReviewService.Restaurant[]> GetAllRestaurantsAsync()
        {
            return base.Channel.GetAllRestaurantsAsync();
        }
        
        public System.Threading.Tasks.Task<RestaurantReviewService.Restaurant[]> GetRestaurantByNameAsync(string RestaurantName)
        {
            return base.Channel.GetRestaurantByNameAsync(RestaurantName);
        }
        
        public System.Threading.Tasks.Task<RestaurantReviewService.Restaurant[]> GetRestaurantByRatingAsync(int Rating)
        {
            return base.Channel.GetRestaurantByRatingAsync(Rating);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IRestaurantReviewService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IRestaurantReviewService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:62080/RestaurantReviewService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return RestaurantReviewServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IRestaurantReviewService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return RestaurantReviewServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IRestaurantReviewService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IRestaurantReviewService,
        }
    }
}
